import type { EnvironmentPreset } from "../catalog";

export const DXVK_PRESETS = [
  {
    key: "DXVK_HUD",
    value: "fps",
    suggestions: [
      "fps",
      "devinfo",
      "devinfo,fps",
      "frametimes",
      "submissions",
      "drawcalls",
      "pipelines",
      "descriptors",
      "memory",
      "allocations",
      "gpuload",
      "version",
      "api",
      "cs",
      "compiler",
      "samplers",
      "swvp",
      "scale=1.5",
      "opacity=0.8",
      "full",
      "1",
      "0",
    ],
    description: "Show the DXVK performance HUD.",
  },
  {
    key: "DXVK_FILTER_DEVICE_NAME",
    value: "",
    description: "Select a Vulkan device by a name substring.",
  },
  {
    key: "DXVK_FILTER_DEVICE_UUID",
    value: "",
    description: "Select a Vulkan device by its 32-character UUID.",
  },
  {
    key: "VK_INSTANCE_LAYERS",
    value: "VK_LAYER_KHRONOS_validation",
    suggestions: ["VK_LAYER_KHRONOS_validation"],
    description: "Enable a Vulkan layer, such as the SDK validation layer.",
  },
  {
    key: "DXVK_LOG_LEVEL",
    value: "debug",
    suggestions: ["none", "error", "warn", "info", "debug"],
    description: "Set the DXVK logging level.",
  },
  {
    key: "DXVK_LOG_PATH",
    value: "none",
    suggestions: ["none"],
    description: "Disable log files or type a directory for them.",
  },
  {
    key: "DXVK_DEBUG",
    value: "capture",
    suggestions: ["capture", "hang", "markers", "validation"],
    description: "Enable a DXVK debugging mode.",
  },
  {
    key: "DXVK_CONFIG_FILE",
    value: "",
    description: "Load settings from a dxvk.conf file.",
  },
  {
    key: "DXVK_CONFIG",
    value: "",
    description: "Set semicolon-separated dxvk.conf options inline.",
  },
  {
    key: "DXVK_SHADER_CACHE",
    value: "0",
    suggestions: ["0", "1"],
    description: "Disable DXVK's internal shader cache.",
  },
  {
    key: "DXVK_SHADER_CACHE_PATH",
    value: "",
    description: "Choose the DXVK shader cache directory.",
  },
  {
    key: "DXVK_HDR",
    value: "1",
    suggestions: ["1", "0"],
    description: "Expose HDR support through DXVK.",
  },
  {
    key: "ENABLE_HDR_WSI",
    value: "1",
    suggestions: ["1", "0"],
    description: "Enable the installed legacy HDR WSI layer for older NVIDIA drivers.",
  },
] as const satisfies readonly EnvironmentPreset[];
