export type ProtonExtraVariant = "GE" | "EM" | "CachyOS";

export interface EnvironmentPreset {
  description: string;
  key: string;
  suggestions?: readonly string[];
  supportedBy?: readonly ProtonExtraVariant[];
  value: string;
}

export interface EnvironmentPresetGroup {
  label: string;
  presets: readonly EnvironmentPreset[];
  source: string;
  sources?: readonly string[];
}

export const DISCORD_BRIDGE_PRESET = {
  key: "PROTON_DISCORD_BRIDGE",
  value: "1",
  suggestions: ["1", "0"],
  description: "Enable Discord Rich Presence through rpc-bridge.",
} as const satisfies EnvironmentPreset;

export const ENVIRONMENT_PRESET_GROUPS = [
  {
    label: "DXVK",
    source: "https://github.com/doitsujin/dxvk/blob/master/README.md#hud",
    sources: [
      "https://github.com/doitsujin/dxvk/blob/master/dxvk.conf",
      "https://github.com/Zamundaaa/VK_hdr_layer",
    ],
    presets: [
      {
        key: "DXVK_HUD",
        value: "fps",
        suggestions: [
          "fps",
          "devinfo",
          "devinfo,fps",
          "frametimes",
          "submissions",
          "drawcalls",
          "pipelines",
          "descriptors",
          "memory",
          "allocations",
          "gpuload",
          "version",
          "api",
          "cs",
          "compiler",
          "samplers",
          "swvp",
          "scale=1.5",
          "opacity=0.8",
          "full",
          "1",
          "0",
        ],
        description: "Show the DXVK performance HUD.",
      },
      {
        key: "DXVK_FILTER_DEVICE_NAME",
        value: "",
        description: "Select a Vulkan device by a name substring.",
      },
      {
        key: "DXVK_FILTER_DEVICE_UUID",
        value: "",
        description: "Select a Vulkan device by its 32-character UUID.",
      },
      {
        key: "VK_INSTANCE_LAYERS",
        value: "VK_LAYER_KHRONOS_validation",
        suggestions: ["VK_LAYER_KHRONOS_validation"],
        description: "Enable a Vulkan layer, such as the SDK validation layer.",
      },
      {
        key: "DXVK_LOG_LEVEL",
        value: "debug",
        suggestions: ["none", "error", "warn", "info", "debug"],
        description: "Set the DXVK logging level.",
      },
      {
        key: "DXVK_LOG_PATH",
        value: "none",
        suggestions: ["none"],
        description: "Disable log files or type a directory for them.",
      },
      {
        key: "DXVK_DEBUG",
        value: "capture",
        suggestions: ["capture", "hang", "markers", "validation"],
        description: "Enable a DXVK debugging mode.",
      },
      {
        key: "DXVK_CONFIG_FILE",
        value: "",
        description: "Load settings from a dxvk.conf file.",
      },
      {
        key: "DXVK_CONFIG",
        value: "",
        description: "Set semicolon-separated dxvk.conf options inline.",
      },
      {
        key: "DXVK_SHADER_CACHE",
        value: "0",
        suggestions: ["0", "1"],
        description: "Disable DXVK's internal shader cache.",
      },
      {
        key: "DXVK_SHADER_CACHE_PATH",
        value: "",
        description: "Choose the DXVK shader cache directory.",
      },
      {
        key: "DXVK_HDR",
        value: "1",
        suggestions: ["1", "0"],
        description: "Expose HDR support through DXVK.",
      },
      {
        key: "ENABLE_HDR_WSI",
        value: "1",
        suggestions: ["1", "0"],
        description: "Enable the installed legacy HDR WSI layer for older NVIDIA drivers.",
      },
    ],
  },
  {
    label: "VKD3D",
    source: "https://github.com/HansKristian-Work/vkd3d-proton#environment-variables",
    sources: ["https://github.com/optiscaler/OptiScaler/wiki/FSR4-Compatibility-List"],
    presets: [
      {
        key: "VKD3D_CONFIG",
        value: "dxr",
        suggestions: [
          "vk_debug",
          "dxr",
          "nodxr",
          "dxr12",
          "single_queue",
          "no_upload_hvv",
          "force_static_cbv",
          "force_host_cached",
          "no_invariant_position",
          "skip_application_workarounds",
          "pipeline_library_app_cache",
          "breadcrumbs",
          "descriptor_qa_checks",
        ],
        description: "Apply one or more comma-separated vkd3d-proton options.",
      },
      {
        key: "VKD3D_DEBUG",
        value: "info",
        suggestions: ["none", "err", "info", "fixme", "warn", "trace"],
        description: "Set the vkd3d-proton logging level.",
      },
      {
        key: "VKD3D_SHADER_DEBUG",
        value: "info",
        suggestions: ["none", "err", "info", "fixme", "warn", "trace"],
        description: "Set the vkd3d-proton shader compiler logging level.",
      },
      {
        key: "VKD3D_LOG_FILE",
        value: "",
        description: "Redirect vkd3d-proton logging to a file.",
      },
      {
        key: "VKD3D_VULKAN_DEVICE",
        value: "0",
        suggestions: ["0", "1", "2", "3"],
        description: "Select a Vulkan device by its zero-based index.",
      },
      {
        key: "VKD3D_FILTER_DEVICE_NAME",
        value: "",
        description: "Select a Vulkan device by a name substring.",
      },
      {
        key: "VKD3D_DISABLE_EXTENSIONS",
        value: "",
        description: "Disable a comma- or semicolon-separated list of Vulkan extensions.",
      },
      {
        key: "VKD3D_TEST_DEBUG",
        value: "1",
        suggestions: ["0", "1", "2"],
        description: "Set the additional vkd3d-proton test debug level.",
      },
      {
        key: "VKD3D_TEST_MATCH",
        value: "",
        description: "Run only a test whose name exactly matches this value.",
      },
      {
        key: "VKD3D_TEST_FILTER",
        value: "",
        description: "Run tests whose names contain this filter.",
      },
      {
        key: "VKD3D_TEST_EXCLUDE",
        value: "",
        description: "Exclude tests whose names occur in this comma-separated list.",
      },
      {
        key: "VKD3D_TEST_PLATFORM",
        value: "wine",
        suggestions: ["wine", "windows", "other"],
        description: "Override the platform assumed by vkd3d-proton tests.",
      },
      {
        key: "VKD3D_TEST_BUG",
        value: "0",
        suggestions: ["0", "1"],
        description: "Disable or enable bug conditions in vkd3d-proton tests.",
      },
      {
        key: "VKD3D_PROFILE_PATH",
        value: "",
        description: "Choose the output prefix for profiling data when supported.",
      },
      {
        key: "VKD3D_SWAPCHAIN_PRESENT_MODE",
        value: "FIFO",
        suggestions: ["IMMEDIATE", "MAILBOX", "FIFO", "FIFO_RELAXED", "FIFO_LATEST_READY"],
        description: "Force a supported Vulkan swapchain present mode.",
      },
      {
        key: "VKD3D_SHADER_CACHE_PATH",
        value: "0",
        suggestions: ["0"],
        description: "Disable the shader cache or choose its directory.",
      },
      {
        key: "VKD3D_SHADER_DUMP_PATH",
        value: "",
        description: "Choose the directory where shader bytecode is dumped.",
      },
      {
        key: "VKD3D_SHADER_OVERRIDE",
        value: "",
        description: "Choose the directory containing hash-named SPIR-V overrides.",
      },
      {
        key: "VKD3D_AUTO_CAPTURE_SHADER",
        value: "",
        description: "Capture with RenderDoc when this shader hash is encountered.",
      },
      {
        key: "VKD3D_AUTO_CAPTURE_COUNTS",
        value: "-1",
        suggestions: ["-1"],
        description: "Choose comma-separated queue-submission indices to capture.",
      },
      {
        key: "VKD3D_SHADER_DEBUG_RING_SIZE_LOG2",
        value: "28",
        suggestions: ["26", "27", "28", "29", "30"],
        description: "Set the log2 host-memory size of the shader debug ring.",
      },
      {
        key: "VKD3D_DESCRIPTOR_QA_LOG",
        value: "",
        description: "Choose the descriptor update log file for QA-enabled builds.",
      },
      {
        key: "VKD3D_FRAME_RATE",
        value: "60",
        suggestions: ["30", "60", "90", "120", "144", "165", "240", "0"],
        description: "Limit the frame rate; use 0 to uncap it.",
      },
      {
        key: "DXIL_SPIRV_CONFIG",
        value: "wmma_rdna3_workaround",
        suggestions: ["wmma_rdna3_workaround"],
        description: "Configure DXIL-SPIRV, including the RDNA 3 WMMA workaround.",
      },
    ],
  },
  {
    label: "Proton",
    source: "https://github.com/ValveSoftware/Proton/blob/proton_11.0/README.md#runtime-config-options",
    presets: [
      {
        key: "PROTON_LOG",
        value: "1",
        suggestions: ["1", "0"],
        description: "Write a Proton debug log for this game.",
      },
      {
        key: "PROTON_LOG_DIR",
        value: "",
        description: "Choose the Proton log output directory.",
      },
      {
        key: "PROTON_WAIT_ATTACH",
        value: "1",
        suggestions: ["1", "0"],
        description: "Wait for a debugger to attach to steam.exe before launch.",
      },
      {
        key: "PROTON_CRASH_REPORT_DIR",
        value: "",
        description: "Choose the directory for Proton crash logs.",
      },
      {
        key: "PROTON_USE_WINED3D",
        value: "1",
        suggestions: ["1", "0"],
        description: "Use OpenGL wined3d instead of DXVK.",
      },
      {
        key: "PROTON_NO_D3D11",
        value: "1",
        suggestions: ["1", "0"],
        description: "Disable Proton's d3d11.dll.",
      },
      {
        key: "PROTON_NO_D3D10",
        value: "1",
        suggestions: ["1", "0"],
        description: "Disable Proton's d3d10.dll and dxgi.dll.",
      },
      {
        key: "PROTON_DXVK_D3D8",
        value: "1",
        suggestions: ["1", "0"],
        description: "Use DXVK's d3d8.dll.",
      },
      {
        key: "PROTON_NO_FSYNC",
        value: "1",
        suggestions: ["1", "0"],
        description: "Disable fsync synchronization.",
      },
      {
        key: "PROTON_NO_NTSYNC",
        value: "1",
        suggestions: ["1", "0"],
        description: "Disable ntsync synchronization.",
      },
      {
        key: "HOST_LC_ALL",
        value: "en_US.UTF-8",
        suggestions: ["en_US.UTF-8", "C.UTF-8"],
        description: "Override the host locale for the game.",
      },
      {
        key: "PROTON_DISABLE_NVAPI",
        value: "1",
        suggestions: ["1", "0"],
        description: "Disable NVIDIA NVAPI support.",
      },
      {
        key: "PROTON_HIDE_NVIDIA_GPU",
        value: "1",
        suggestions: ["1", "0"],
        description: "Report NVIDIA GPUs as AMD for compatibility.",
      },
      {
        key: "PROTON_FORCE_LARGE_ADDRESS_AWARE",
        value: "1",
        suggestions: ["1", "0"],
        description: "Force LARGE_ADDRESS_AWARE on game executables.",
      },
      {
        key: "PROTON_HEAP_DELAY_FREE",
        value: "1",
        suggestions: ["1", "0"],
        description: "Delay heap frees for applications with use-after-free bugs.",
      },
      {
        key: "PROTON_SET_GAME_DRIVE",
        value: "1",
        suggestions: ["1", "0"],
        description: "Create an S: drive pointing to the game's Steam library.",
      },
      {
        key: "PROTON_OLD_GL_STRING",
        value: "1",
        suggestions: ["1", "0"],
        description: "Shorten the reported OpenGL extension string for old games.",
      },
      {
        key: "WINE_DO_NOT_CREATE_DXGI_DEVICE_MANAGER",
        value: "1",
        suggestions: ["1", "0"],
        description: "Work around video issues caused by DXGI device-manager support.",
      },
      {
        key: "WINE_DISABLE_VULKAN_OPWR",
        value: "1",
        suggestions: ["1", "0"],
        description: "Disable Vulkan other-process window rendering.",
      },
      {
        key: "WINE_FULLSCREEN_INTEGER_SCALING",
        value: "1",
        suggestions: ["1", "0"],
        description: "Enable sharp integer scaling for fullscreen games.",
      },
      {
        key: "WINE_USE_KWIN_HACKS",
        value: "1",
        suggestions: ["1", "0"],
        description: "Enable KDE-specific Wine windowing workarounds.",
      },
      {
        key: "PROTON_USE_XALIA",
        value: "1",
        suggestions: ["1", "0"],
        description: "Enable or disable Xalia gamepad UI support.",
      },
      {
        key: "FNA3D_FORCE_DRIVER",
        value: "D3D11",
        suggestions: ["D3D11"],
        description: "Force FNA3D games to use the D3D11 renderer.",
      },
      {
        key: "GST_GL_WINDOW",
        value: "",
        description: "Override the GStreamer OpenGL window backend.",
      },
      {
        key: "PROTON_ENABLE_HDR",
        value: "1",
        suggestions: ["1", "0"],
        description: "Enable HDR in supported custom Proton builds; EM HDRTEST builds exclude it.",
        supportedBy: ["GE", "EM"],
      },
      {
        key: "DXVK_NO_HDR",
        value: "1",
        suggestions: ["1", "0"],
        description: "Force HDR off in supported custom Proton builds.",
        supportedBy: ["GE", "EM", "CachyOS"],
      },
      {
        key: "PROTON_DUMP_DEBUG_COMMANDS",
        value: "1",
        suggestions: ["1", "0"],
        description: "Write useful game debug scripts under PROTON_DEBUG_DIR.",
        supportedBy: ["GE"],
      },
      {
        key: "PROTON_DEBUG_DIR",
        value: "/tmp",
        description: "Choose the root directory for Proton-GE debug scripts.",
        supportedBy: ["GE"],
      },
      {
        key: "PROTON_USE_WINED3D11",
        value: "1",
        suggestions: ["1", "0"],
        description: "Legacy Proton-GE alias for PROTON_USE_WINED3D.",
        supportedBy: ["GE"],
      },
      {
        key: "PROTON_NO_D3D12",
        value: "1",
        suggestions: ["1", "0"],
        description: "Disable Direct3D 12 support in Proton-GE.",
        supportedBy: ["GE"],
      },
      {
        key: "PROTON_NO_D3D9",
        value: "1",
        suggestions: ["1", "0"],
        description: "Disable Direct3D 9 support in Proton-GE.",
        supportedBy: ["GE"],
      },
      {
        key: "PROTON_NO_ESYNC",
        value: "1",
        suggestions: ["1", "0"],
        description: "Disable esync in Proton-GE.",
        supportedBy: ["GE"],
      },
      {
        key: "PROTON_ENABLE_NVAPI",
        value: "1",
        suggestions: ["1", "0"],
        description: "Enable NVIDIA NVAPI support in Proton-GE.",
        supportedBy: ["GE"],
      },
      {
        key: "PROTON_USE_SECCOMP",
        value: "1",
        suggestions: ["1", "0"],
        description: "Legacy Proton-GE README option for the seccomp syscall-emulation filter.",
        supportedBy: ["GE"],
      },
      {
        key: "PROTON_NO_WRITE_WATCH",
        value: "1",
        suggestions: ["1", "0"],
        description: "Disable ntdll memory write watches for specific compatible games.",
        supportedBy: ["GE"],
      },
      {
        key: "WINE_FULLSCREEN_FSR",
        value: "1",
        suggestions: ["1", "0"],
        description: "Enable Proton-GE's fullscreen FSR patch for Vulkan games.",
        supportedBy: ["GE", "CachyOS"],
      },
      {
        key: "WINE_FULLSCREEN_FSR_STRENGTH",
        value: "2",
        suggestions: ["0", "1", "2", "3", "4", "5"],
        description: "Set fullscreen FSR sharpening from 0 (most) to 5 (least).",
        supportedBy: ["GE", "CachyOS"],
      },
      {
        key: "WINE_FULLSCREEN_FSR_CUSTOM_MODE",
        value: "",
        description: "Set the WIDTHxHEIGHT fake resolution used by fullscreen FSR.",
        supportedBy: ["GE", "CachyOS"],
      },
      {
        key: "COPYPREFIX",
        value: "1",
        suggestions: ["1", "0"],
        description: "Copy the prefix and shader cache between local and game storage.",
        supportedBy: ["GE"],
      },
      {
        key: "PROTON_FSR4_UPGRADE",
        value: "1",
        suggestions: ["1", "0"],
        description: "Upgrade supported FSR 3.1 games to FSR 4, optionally pinning a version.",
        supportedBy: ["GE", "EM", "CachyOS"],
      },
      {
        key: "FSR4_UPGRADE",
        value: "1",
        suggestions: ["1", "0"],
        description: "Enable the low-level FSR 4 DLL injection path.",
        supportedBy: ["GE", "EM", "CachyOS"],
      },
      {
        key: "PROTON_FSR4_INDICATOR",
        value: "1",
        suggestions: ["1", "0"],
        description: "Show the FSR 4 watermark.",
        supportedBy: ["GE", "CachyOS"],
      },
      {
        key: "PROTON_FSR4_RDNA3_UPGRADE",
        value: "1",
        suggestions: ["1", "0"],
        description: "Upgrade FSR 3.1 to FSR 4 with Proton-GE's RDNA 3 workarounds.",
        supportedBy: ["GE"],
      },
      {
        key: "PROTON_FSR3_UPGRADE",
        value: "1",
        suggestions: ["1", "0"],
        description: "Enable Proton-GE's FSR 3 upgrade path.",
        supportedBy: ["GE"],
      },
      {
        key: "PROTON_DLSS_UPGRADE",
        value: "1",
        suggestions: ["1", "0"],
        description: "Upgrade DLSS DLLs, optionally pinning the documented version prefix.",
        supportedBy: ["GE", "CachyOS"],
      },
      {
        key: "PROTON_DLSS_INDICATOR",
        value: "1",
        suggestions: ["1", "0"],
        description: "Show the DLSS status overlay.",
        supportedBy: ["GE", "CachyOS"],
      },
      {
        key: "PROTON_XESS_UPGRADE",
        value: "1",
        suggestions: ["1", "0"],
        description: "Upgrade the bundled XeSS DLLs.",
        supportedBy: ["GE", "CachyOS"],
      },
      {
        key: "PROTON_USE_SDL",
        value: "1",
        suggestions: ["1", "0"],
        description: "Use SDL input instead of HIDRAW and Steam Input.",
        supportedBy: ["GE", "EM", "CachyOS"],
      },
      {
        key: "PROTON_PREFER_SDL",
        value: "1",
        suggestions: ["1", "0"],
        description: "Prefer SDL input instead of HIDRAW and Steam Input.",
        supportedBy: ["GE", "EM", "CachyOS"],
      },
      {
        key: "PROTON_USE_WAYLAND",
        value: "1",
        suggestions: ["1", "0"],
        description: "Enable the native Wine Wayland driver.",
        supportedBy: ["GE", "EM", "CachyOS"],
      },
      {
        key: "PROTON_ENABLE_WAYLAND",
        value: "1",
        suggestions: ["1", "0"],
        description: "Enable the native Wine Wayland driver.",
        supportedBy: ["GE", "EM", "CachyOS"],
      },
      {
        key: "PROTON_USE_WOW64",
        value: "1",
        suggestions: ["1", "0"],
        description: "Enable the new WoW64 mode in supported custom Proton builds.",
        supportedBy: ["GE", "EM"],
      },
      {
        key: "WAYLANDDRV_PRIMARY_MONITOR",
        value: "",
        description: "Choose the primary monitor used by the Wine Wayland driver.",
        supportedBy: ["GE", "EM", "CachyOS"],
      },
      {
        key: "PROTON_ENABLE_MEDIACONV",
        value: "1",
        suggestions: ["1", "0"],
        description: "Enable the winegstreamer media converter.",
        supportedBy: ["GE", "EM", "CachyOS"],
      },
      {
        key: "WAYLANDDRV_RAWINPUT",
        value: "0",
        suggestions: ["0", "0.5", "1"],
        description: "Disable raw input or set a positive Wine Wayland sensitivity.",
        supportedBy: ["GE", "EM", "CachyOS"],
      },
      {
        key: "WINE_BLOCK_HOSTS",
        value: "",
        description: "Block up to 16 comma- or semicolon-separated hosts in Wine.",
        supportedBy: ["GE", "CachyOS"],
      },
      {
        key: "WINEALSA_CHANNELS",
        value: "2",
        suggestions: ["2", "4", "6", "8"],
        description: "Set the Wine ALSA speaker count.",
        supportedBy: ["GE", "CachyOS"],
      },
      {
        key: "WINEALSA_SPATIAL",
        value: "1",
        suggestions: ["1", "0"],
        description: "Enable spatial-audio downmixing in Wine ALSA.",
        supportedBy: ["GE", "CachyOS"],
      },
      {
        key: "PROTON_ADD_CONFIG",
        value: "sdlinput",
        suggestions: ["sdlinput", "fsr4", "fsr4rdna3", "hdr", "wayland", "wow64", "nontsync"],
        description: "Apply one or more comma-separated Proton-EM compatibility options.",
        supportedBy: ["EM"],
      },
      {
        key: "PROTON_MLFG_UPGRADE",
        value: "0",
        suggestions: ["0", "1"],
        description: "Disable or enable MLFG while an FSR 4 upgrade is active.",
        supportedBy: ["EM", "CachyOS"],
      },
      {
        key: "PROTON_DXVK_SAREK",
        value: "1",
        suggestions: ["1", "0"],
        description: "Use DXVK-Sarek for older Vulkan GPUs; avoid anti-cheat games.",
        supportedBy: ["CachyOS"],
      },
      {
        key: "PROTON_DXVK_LOWLATENCY",
        value: "1",
        suggestions: ["1", "0"],
        description: "Use the low-latency DXVK fork.",
        supportedBy: ["CachyOS"],
      },
      {
        key: "PROTON_D7VK_DDRAW",
        value: "1",
        suggestions: ["1", "0"],
        description: "Use D7VK's ddraw.dll for older DirectX games.",
        supportedBy: ["CachyOS"],
      },
      {
        key: "PROTON_FFX3_UPGRADE",
        value: "1",
        suggestions: ["1", "0"],
        description: "Upgrade the bundled FidelityFX 3 DLLs.",
        supportedBy: ["CachyOS"],
      },
      {
        key: "PROTON_FFX4_UPGRADE",
        value: "1",
        suggestions: ["1", "0"],
        description: "Upgrade the bundled FidelityFX 4 DLLs.",
        supportedBy: ["CachyOS"],
      },
      {
        key: "PROTON_NVIDIA_LIBS",
        value: "1",
        suggestions: ["1", "0"],
        description: "Enable all alternative NVIDIA libraries.",
        supportedBy: ["CachyOS"],
      },
      {
        key: "PROTON_NVIDIA_LIBS_NO_32BIT",
        value: "1",
        suggestions: ["1", "0"],
        description: "Use only the 64-bit alternative NVIDIA libraries.",
        supportedBy: ["CachyOS"],
      },
      {
        key: "PROTON_NVIDIA_NVCUDA",
        value: "1",
        suggestions: ["1", "0"],
        description: "Enable the alternative nvcuda.dll.",
        supportedBy: ["CachyOS"],
      },
      {
        key: "PROTON_NVIDIA_NVENC",
        value: "1",
        suggestions: ["1", "0"],
        description: "Enable the alternative NVIDIA encoder DLLs.",
        supportedBy: ["CachyOS"],
      },
      {
        key: "PROTON_NVIDIA_NVML",
        value: "1",
        suggestions: ["1", "0"],
        description: "Enable the alternative nvml.dll.",
        supportedBy: ["CachyOS"],
      },
      {
        key: "PROTON_NVIDIA_NVOPTIX",
        value: "1",
        suggestions: ["1", "0"],
        description: "Enable the alternative nvoptix.dll.",
        supportedBy: ["CachyOS"],
      },
      {
        key: "PROTON_NO_WM_DECORATION",
        value: "1",
        suggestions: ["1", "0"],
        description: "Use Wine decorations instead of window-manager decorations.",
        supportedBy: ["CachyOS"],
      },
      {
        key: "PROTON_USE_PIPEWIRE",
        value: "0",
        suggestions: ["0", "1"],
        description: "Disable the Wine PipeWire driver, which is enabled by default.",
        supportedBy: ["CachyOS"],
      },
      {
        key: "PROTON_NO_STEAMINPUT",
        value: "1",
        suggestions: ["1", "0"],
        description: "Disable Steam Input integration in Proton-CachyOS.",
        supportedBy: ["CachyOS"],
      },
      {
        key: "PROTON_LOCAL_SHADER_CACHE",
        value: "1",
        suggestions: ["1", "0"],
        description: "Enable a per-game local shader cache.",
        supportedBy: ["CachyOS"],
      },
      {
        key: "PROTON_MEDIA_FORCE_GST",
        value: "1",
        suggestions: ["1", "0"],
        description: "Try GStreamer for broken cutscene playback.",
        supportedBy: ["CachyOS"],
      },
      {
        key: "PROTON_GST_VIDEO_ORIENTATION",
        value: "auto",
        description: "Set GStreamer video rotation or flip behavior.",
        supportedBy: ["CachyOS"],
      },
      {
        key: "DXVK_NVAPI_VKREFLEX",
        value: "1",
        suggestions: ["1", "0"],
        description: "Enable the Vulkan Reflex layer.",
        supportedBy: ["CachyOS"],
      },
      {
        key: "LOW_LATENCY_LAYER",
        value: "1",
        suggestions: ["1", "0"],
        description: "Enable CachyOS's low-latency Vulkan layer.",
        supportedBy: ["CachyOS"],
      },
      {
        key: "WINE_AUDIO_DRIVER",
        value: "pipewire,pulse,alsa",
        suggestions: ["pipewire,pulse,alsa", "pipewire", "pulse", "alsa"],
        description: "Choose Wine audio drivers in preference order.",
        supportedBy: ["CachyOS"],
      },
      {
        ...DISCORD_BRIDGE_PRESET,
        supportedBy: ["CachyOS"],
      },
    ],
    sources: [
      "https://github.com/GloriousEggroll/proton-ge-custom#options",
      "https://github.com/Etaash-mathamsetty/Proton/blob/em-10/docs/EM-ADDITIONS.md",
      "https://github.com/CachyOS/proton-cachyos#proton-cachyos-config-options",
      "https://github.com/GStreamer/gstreamer",
    ],
  },
] as const satisfies readonly EnvironmentPresetGroup[];

export const ENVIRONMENT_PRESETS = ENVIRONMENT_PRESET_GROUPS.flatMap<EnvironmentPreset>(
  ({ presets }) => presets,
);
